# Site settings
title: "Welcome to Zoku Eigou's Personal Station!"
subtitle: "欢迎来到粟英豪的个人站！"
author: "Su Yinghao"
description: "This is a blog about something I have learned. Maybe there are lots of mistakes."
keywords: "Linux, Ruby, Python, Docker"
biography: "My name is Su Yinghao, and Zoku Eigou is the Japanese pronunciation of my name. I am a student of ECUST."

baseurl: ""
url: ""

github_username: TreeShadeZoku

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
